### ISSUE TITLE
Fatal errors while backing up

### ISSUE THREAD

**Issue by gottsman** [Minituff/nautical-backup#117]
I've had the error only with the Radarr and Sonarr containers. The src is the local file system and the destination is an NFS mount within Docker Compose.

Not sure if its how the Linux Server teams build their images. Here is the debug log from the console:

    image: lscr.io/linuxserver/radarr:latest
    image: lscr.io/linuxserver/sonarr:latest

```
DEBUG: Checking  radarr.
DEBUG: Enabling radarr based on label.
DEBUG: Skipping stopping of radarr because of label.
INFO: Backing up radarr data...
DEBUG: RUNNING: 'rsync -ahq --exclude='*.log' --exclude='*.txt' --no-owner --no-perms --no-group /app/source/radarr/ /app/destination/radarr/'
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: fatal: timed out
INFO: radarr completed.
```

**Comment by Minituff** [comment]
I haven't seen an `s6-sudoc` error before. I also use the [S6 Overlay](https://github.com/just-containers/s6-overlay) like LinuxServer does for Sonarr and Radarr, but I think this error is on the Nautical end.

I also see that you have some custom `rsync` arguments applied. If you remove `rsync` args do you still get this error?

Could you post your Nautical and Sonarr/Radarr config? I can try to replicate this on my side.

**Comment by gottsman** [comment]
I get permission errors without the custom rsync commands -- I believe its permissions issues with my local Synology. I've had the same issues with my custom written scripts. Here is the relevant parts of my docker-compose.yaml file.

```
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    profiles: ['all', 'media']
    depends_on:
      - prowlarr
      - dozzle
      - transmission
    networks:
      - homelab
    expose:
      - 7878
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPDATA}/radarr:/config
      - movies:/movies
      - transmission:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:radarr-striptracks
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entryPoints=https"
      - "traefik.http.routers.radarr.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "nautical-backup.enable=true"
      - "nautical-backup.stop-before-backup=false"

  nautical-backup:
    image: minituff/nautical-backup:1.3
    profiles: ['all', 'backup']
    networks:
      - homelab
    container_name: nautical-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPDATA}:/app/source
      - nautical:/app/destination
    environment: # Optional variables
      - TZ=America/New_York
      - REQUIRE_LABEL=true
      - BACKUP_ON_START=true
      # - RSYNC_CUSTOM_ARGS=--exclude='*.log' --exclude='*.txt' --no-owner --no-perms --no-group

volumes:
  nautical:
    driver_opts:
      type: nfs
      o: "addr=192.168.3.2,nolock,soft,rw"
      device: ":/volume1/Nautical"
```
