### ISSUE TITLE
rsync working as intended

### ISSUE THREAD

**Issue by wedge-kc** [Minituff/nautical-backup#225]
Thanks for the software.  Very handy.

I am having an issue with rsync.  According the log, my custom rsync label in Emby is being used to backup the volume.

```
2024-04-30 04:00:04.524252 - INFO: Backing up emby...
2024-04-30 04:00:04.524450 - DEBUG: RUNNING: 'rsync -raq --exclude='cache' --exclude='transcoding-temp' --exclude='.log' --exclude='.txt' /app/source/emby/ /app/destination/2024-04-30/emby/'
2024-04-30 04:00:05.953838 - INFO: Starting emby...
2024-04-30 04:00:06.283771 - INFO: Backup of emby complete!
``` 

However, the excluded directories,  *.log and *.txt are all still copied to the destination directory as if the custom command was not used.  If I use the same rsync command from the log and run it inside the container, it seems to work correctly and excludes the desired directories and files.  Thanks.

```
services:
  nautical-backup:
    image: minituff/nautical-backup:2.3
    container_name: nautical-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/chris/docker:/app/source
      - /mnt/media/nautical-backup:/app/destination
    environment: # Optional variables 
      - TZ=Asia/Phnom_Penh
      - CRON_SCHEDULE=0 4 * * *
      - USE_DEST_DATE_FOLDER=true
      - REPORT_FILE_LOG_LEVEL=DEBUG
      - POST_BACKUP_CURL=tar -czf /app/destination/$(date +"%Y-%m-%d").tar.gz /app/destination/$(date +"%Y-%m-%d") | xargs rm -R /app/destination/$(date +"%Y-%m-%d")
      - SKIP_CONTAINERS=nautical-backup,portainer
```
