### ISSUE TITLE
Backup to two locations

### ISSUE THREAD

**Issue by holocronology** [Minituff/nautical-backup#265]
Is it possible to configure so that backups are generated in two locations?

**Comment by Minituff** [comment]
Hmm, not by default. I think you could add the [Additional Folders](https://minituff.github.io/nautical-backup/arguments/#additional-folders) variable and use that to go to a second location.

You could also use the [Lifecycle hooks](https://minituff.github.io/nautical-backup/labels/?h=life#lifecycle-hooks) to run a simple copy command to another location once the backup is complete.

**Comment by Minituff** [comment]
Hi @holocronology ,

I did some work on this today and this feature is now native. Update to [v2.5.0](https://github.com/Minituff/nautical-backup/releases/tag/V2.5.0) to test it out.

I'm going to close the issue for now (assuming it works), but if it doesn't feel free to re-open this issue or make a new one.

Closed in https://github.com/Minituff/nautical-backup/pull/298

**Comment by holocronology** [comment]
I will test it out. Currently I have two instances of the container running. :-)

**Comment by Minituff** [comment]
That's really smart honestly. Maybe it would have been easier for me to just recommend that 😎.


I also just noticed an issue with version 2.5.0... the secondary locations are being skipped in favor of the Additional Folders variable. I'd hold off on testing it out until I get a patch in.

**Comment by holocronology** [comment]
It was the way... ;-)

One container would be better, still, IMO.  But yes, as best I can tell it isn't working. Granted, my container still indicates version 2.4.3, so that might be part of it. I tried to update it every which way to Sunday, but it wouldn't. Could it be that the version tad internally is still at 2.4.3?

**Comment by holocronology** [comment]
Just for reference, this is what I basically do now:

```
  nautical-backup-ext:
    image: minituff/nautical-backup:2
    container_name: nautical-backup-ext
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /volume2/docker:/app/source 
      - /volumeUSB1/usbshare/backup/nbu-docker:/app/destination 
    environment: # Optional variables 
      - TZ=America/New_York 
      - CRON_SCHEDULE=33 3 * * * 
      - SKIP_CONTAINERS=xxxxx
      - REPORT_FILE=true
      - BACKUP_ON_START=false
      - OVERRIDE_SOURCE_DIR=xxxxx
    restart: unless-stopped

  nautical-backup:
    image: minituff/nautical-backup:2
    container_name: nautical-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /volume2/docker:/app/source 
      - /volume1/backups/nbu-docker:/app/destination 
    environment: # Optional variables 
      - TZ=America/New_York 
      - CRON_SCHEDULE=0 3 * * * 
      - SKIP_CONTAINERS=xxxxx
      - REPORT_FILE=true
      - BACKUP_ON_START=false
      - OVERRIDE_SOURCE_DIR=xxxxx
      #- SECONDARY_DEST_DIRS=/volumeUSB1/usbshare/backup/nbu-docker
    restart: unless-stopped
```

**Comment by Minituff** [comment]
> Could it be that the version tad internally is still at 2.4.3?

It shouldn't, no--atleast I've never seen that before. I was able to pull down `v.2.5.1` from DockerHub, so I'm guessing you haven't gotten the latest image to pull yet.

 You should be seeing `INFO: Nautical Backup Version: 2.5.1` in the logs otherwise you wont be getting the new features.

Have you checked out the [Updating Nautical](https://minituff.github.io/nautical-backup/updates/) part of the documentation? You should be able to hard-code it to `2.5.1` which will force Docker to pull that version for now.

---

Also, looking at the this part of your YML:
> #- SECONDARY_DEST_DIRS=/volumeUSB1/usbshare/backup/nbu-docker

I don't think this part of the config will work since the Nautical container won't have access to `/volumeUSB1/usbshare` without you mounting it first. I think it should look like this:

```yaml
  nautical-backup:
    image: minituff/nautical-backup:2
    container_name: nautical-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /volume2/docker:/app/source 
      - /volume1/backups/nbu-docker:/app/destination
      - /volumeUSB1/usbshare/backup/nbu-docker:/nbu-docker  # <--- Here we mount the secondary location
    environment: # Optional variables 
      - TZ=America/New_York 
      - CRON_SCHEDULE=0 3 * * * 
      - SKIP_CONTAINERS=xxxxx
      - REPORT_FILE=true
      - BACKUP_ON_START=false
      - OVERRIDE_SOURCE_DIR=xxxxx
      - SECONDARY_DEST_DIRS=/nbu-docker  # <---- This is the path inside Nautical
    restart: unless-stopped
```

I do really like the idea of backing up your volumes to a USB, I might start doing that too.
