### ISSUE TITLE
Labels do not work

### ISSUE THREAD

**Issue by pendraggon87** [Minituff/nautical-backup#305]
I have configured the backup container to require the use of the nautical-backup.enable label.  However, even when I use this label on numerous containers, nautical-backup will skip backing them up.

**Comment by Minituff** [comment]
Hi, 

Could you set the log level to `TRACE` and attach your Nautical config and logs as well as one of the skipped container's config.

**Comment by pendraggon87** [comment]
I see errors like this in TRACE:
DEBUG: paperless-webserver-1 - Source directory '/app/source/paperless-webserver-1' does not exist. Skipping

**Comment by Minituff** [comment]
Ahh okay I think I understand. It seems like the `nautical-backup.enable` label is working properly. The issue seems to be that the `/app/source/paperless-webserver-1` doesn't exist inside Nautical.

Take a look at this example:


```yaml
services:
  nautical-backup:
    image: minituff/nautical-backup:2 
    container_name: nautical-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /config:/config
      - /path/to/docker/volumes:/app/source  # <---  Source
      - /destination:/app/destination
```


The most relevant line is this one: `- /path/to/docker/volumes:/app/source`.

Here we are telling Docker to pass all the files/folders from `/path/to/docker/volumes` into the Nautical container at the path `/app/source`.

In your case, can you check to make sure your Source path is mapped correctly? Additionally, the folder `paperless-webserver-1` needs to exist inside the Source path so it can be picked up.

**Comment by Minituff** [comment]
> However, nautical-backup seems to be looking for the volume to be the same name as the container? 

Yes, this is the default action, but you have a few options if you don't want to rename the source folders.

1. Using overrides via a global [Environment variable](https://minituff.github.io/nautical-backup/arguments/#override-source-directory)

Here you modify the Nautical config
```yaml 
services:
  nautical-backup:
    image: minituff/nautical-backup:2 
    container_name: nautical-backup
    environment:
      - OVERRIDE_SOURCE_DIR=authentik-postgres-1:authentik_database
 ```


3. Using overrides via a global via a [label](https://minituff.github.io/nautical-backup/labels/#override-source-directory-name) on each container. 

Here you modify the config on each container

```yaml 
services:
  authentic-postgres
    image: authentic/imagename:latest
    container_name: authentic-something
    labels:
      - nautical-backup.override-source-dir=authentik_database
 ```
