### ISSUE TITLE
Enhancement: Add time taken for last backup to complete to API

### ISSUE THREAD

**Issue by robflate** [Minituff/nautical-backup#309]
Would it be possible to add how long the latest backup took to complete to the API? Something like `last_cron_timetaken` or something?

**Comment by Minituff** [comment]
Yeah I should be able to add that. In this case it will report back the time taken for all the containers combined.

**Comment by robflate** [comment]
Thanks! That sounds ideal.

**Comment by Minituff** [comment]
Okay, I updated the API to now return `last_backup_seconds_taken` as part of the `dashboard` API endpoint in version [v2.6.0-alpha1](https://github.com/Minituff/nautical-backup/releases/tag/v2.6.0-alpha1) and PR https://github.com/Minituff/nautical-backup/pull/311

Could you test it out and let me know what you think?

How to force update the YML
```yaml
    image: minituff/nautical-backup:2.6.0-alpha1
```

**Comment by Minituff** [comment]
Happy to hear it. 

Could you share your homepage config? I'm curious how you translated the Seconds to Minutes for the duration.

**Comment by robflate** [comment]
```
    - Nautical Backup:
        icon: https://raw.githubusercontent.com/Minituff/nautical-backup/main/docs/media/Logo-large.png
        description: Docker Volume Backups
        widget:
            type: customapi
            url: http://nautical-backup:8069/api/v1/nautical/dashboard
            username: {{HOMEPAGE_VAR_NAUTICAL_HTTP_REST_API_USERNAME}}
            password: {{HOMEPAGE_VAR_NAUTICAL_HTTP_REST_API_PASSWORD}}
            method: GET
            mappings:
            - field: errors
              label: Errors
            - field: last_cron
              label: Last Run
              format: relativeDate
            - field: last_backup_seconds_taken
              label: duration
              format: number
              suffix: mins
              scale: 1/60
```
