### ISSUE TITLE
Run container as non-root user

### ISSUE THREAD

**Issue by robflate** [Minituff/nautical-backup#314]
Is it possible to run the container as a non-root user, specifically I want to run it as my host user either by passing `PUID` and `PGID` env vars or with `user: 1000:1000`.

**Comment by Minituff** [comment]
Yes it is. I tested it on my end and it should work. You just need to ensure the user you use has access to both the `source`, `config` and `destination` folder.

You should be able to use it like this:


```yaml
services:
  nautical-backup:
    image: minituff/nautical-backup:2 
    container_name: nautical-backup
    user: 1000:1000  # <--- override default `root` user
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /config:/config
      - /source:/app/source
      - /destination:/app/destination
    environment: # Optional variables
      - TZ=America/Los_Angeles
      - CRON_SCHEDULE=0 4 * * *
      - SKIP_CONTAINERS=example1,example2,example3
  ```

Let me know if this works for you. I can also update the docs so everyone else knows that it's supported.
