### ISSUE TITLE
Container with override-source-dir label does not support comma values

### ISSUE THREAD

**Issue by aprice30** [Minituff/nautical-backup#323]
So I have the following compose.yaml
```yaml
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager_app
    restart: unless-stopped
    labels:
      nautical-backup.enable: true
      nautical-backup.group: npm
    ports:
      - '80:80'       # HTTP
      - '81:81'       # Admin UI
      - '443:443'     # HTTPS
    networks:
      - homelab
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: $MYSQL_USER
      DB_MYSQL_PASSWORD: $MYSQL_PASSWORD
      DB_MYSQL_NAME: $MYSQL_DATABASE
    volumes:
      - app_data:/data
      - app_letsencrypt:/etc/letsencrypt
  db:
    image: 'mariadb:latest'
    container_name: nginx_proxy_manager_db
    restart: unless-stopped
    labels:
      nautical-backup.enable: true
      nautical-backup.group: npm
      nautical-backup.override-source-dir: nginxproxymanager_db_mysql
    networks:
      - homelab
    env_file:
      - stack.env
    volumes:
      - db_mysql:/var/lib/mysql
networks:
  homelab:
    external: true
volumes:
  app_data:
  app_letsencrypt:
  db_mysql:
```
As you can see it has 2 services and the `app` service has 2 volumes. As I am using portainer and compose the volumes are called:
* nginxproxymanager_app_data
* nginxproxymanager_app_letsencrypt

I tried to apply the following label but it is ignored and the volumes are skipped (https://minituff.github.io/nautical-backup/labels/#override-source-directory-name)
```
nautical-backup.override-source-dir=nginxproxymanager_app_data,nginxproxymanager_app_letsencrypt
```

To get this to work I had to use the global VAR
```
OVERRIDE_SOURCE_DIR=nginx_proxy_manager_app:nginxproxymanager_app_data,nginx_proxy_manager_app:nginxproxymanager_app_letsencrypt
```

So it seems the container label does not allow a comma separated list but the global does. Would be nice if they were similar as its annoying most config is at my container level except this one.
