### ISSUE TITLE
override-source-dir is not respected when USE_DEST_DATE_FOLDER=true

### ISSUE THREAD

**Issue by mrjk** [Minituff/nautical-backup#383]
For this given configuration:
```yaml
services:
  nautical:
    image: minituff/nautical-backup:2.8
    # ...
    environment:
      - USE_DEST_DATE_FOLDER=true
      - DEST_DATE_FORMAT=infra_archives_paperless/%Y-%m-%d_%H-%M-%S

  webserver:
    labels:
      - nautical-backup.override-source-dir=media
      - nautical-backup.additional-folders=data,share

  db: 
    labels:
      - nautical-backup.override-source-dir=db_data
```

I get this:
```
`-- infra_archives_paperless
    |-- 2024-11-24_15-47-32
    |   |-- infra_archives_paperless-ngx-db-1         # bug here: override-source-dir not respected anymore, expected db_data instead
    |   |-- infra_archives_paperless-ngx-webserver-1  # Other bug here, expected media as name
    |   |-- data                                      # Work well here and below
    |   `-- share
    |-- 2024-11-24_15-51-12
    |   |-- infra_archives_paperless-ngx-db-1         # Same here
    |   |-- infra_archives_paperless-ngx-webserver-1  # Same here
    |   |-- data
    |   `-- share
    `-- Backup\ Report\ -\ 2024-11-24.txt
```

I'm starting investigation on this one :)
