### ISSUE TITLE
run manually

### ISSUE THREAD

**Issue by cirrusflyer** [Minituff/nautical-backup#434]
How do you kick off a backup manually?  I've looked around on the wiki and here and can't find.  Apologies.

**Comment by Minituff** [comment]
Hi @cirrusflyer,

There are a couple ways you can do this:

1. Start the container with the [BACKUP_ON_START=true](https://minituff.github.io/nautical-backup/arguments/#backup-on-start) environment variable. 
2. Use the [REST API](https://minituff.github.io/nautical-backup/rest-api/). Once you have it setup you can tell Nautical to backup at anytime
3. Exec into the container and run the backup manually.
    ```bash
    docker exec -it nautical-backup /usr/bin/with-contenv nautical
    ```
    * This will immediately kickoff the backup as if the CRON schedule triggered it.
    * This one wasn't in the docs, so now that you bring it up I should probably add it.

**Comment by Minituff** [comment]
Yeah thats defintely not supposed to happen. This is a bug where Nautical tries to back itself up. 

Make sure you set the container_name like this in the YML and it should ignore itself. For extra security you can add the label to Nautical so it will bee ignored. I thought I had this by default, but Ill check again.

```yml
services:
  nautical-backup:
    image: minituff/nautical-backup:2.10 
    container_name: nautical-backup # <--- HERE
  labels:
    - "nautical-backup.enable=false".  # <----- HERE AGAIN
```
