### ISSUE TITLE
Rsync exclude of certain Plex folders not working

### ISSUE THREAD

**Issue by correctomundo79** [Minituff/nautical-backup#496]
First of all: great tool! I really like the simplicity of it in combination with the flexibility the labels provide!

I'm not sure if this is a bug, or that I'm using the incorrect syntax, but here's my issue: I'm trying to exclude 3 folders from the Plex container, because these will automatically be recreated when they are missing. However, Nautical doesn't skip them.

I'm using the following nautical compose file:

```yaml
services:
  nautical-backup:
    image: minituff/nautical-backup:2.13
    container_name: nautical-backup
    networks:
      - nautical
      - socket_proxy
    volumes:
      - /mnt/user/appdata/nautical/config:/config
      - /mnt/user/appdata:/app/source
      - /mnt/user/backup/nautical:/app/destination
    environment:
      - TZ=Europe/Amsterdam
      - "CRON_SCHEDULE=0 2 * * *"
      - LOG_LEVEL=DEBUG
      - REQUIRE_LABEL=true
      - USE_DEFAULT_RSYNC_ARGS=false
      - DOCKER_HOST=tcp://socket-proxy:2375
```

The Plex container I'm backing up has the following labels:

```yaml
    labels:
      - nautical-backup.enable=true
      - nautical-backup.stop-before-backup=false
      - nautical-backup.stop-timeout=20
      - "nautical-backup.rsync-custom-args=-vra --exclude='Library/Application Support/Plex Media Server/Cache' --exclude='Library/Application Support/Plex Media Server/Media' --exclude='Library/Application Support/Plex Media Server/Metadata'"
```

No errors are shown in the log, but when I run the same command in the docker cli, it does exclude the folders correctly:

```bash
docker exec -it nautical-backup bash
rsync -vra --exclude='Library/Application Support/Plex Media Server/Cache' --exclude='Library/Application Support/Plex Media Server/Media' --exclude='Library/Application Support/Plex Media Server/Metadata' /app/source/plex/ /app/destination/plex/
```

Can you confirm that the label syntax is correct?

I've wondered if the fact that there are spaces in the path is the cause, but even if you just name the folder 'Cache' (--exclude='Cache') for instance, it's still not excluded.
